title: Riiichard
author: Richard Chan
email: anonymous@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Eternal optimist

# social links
twitter_username: richardchan
github_username:  richardchan

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
